### ISSUE TITLE
portable version downoad

### ISSUE THREAD

**Issue by fleapower** [jdckr/todotxt.net#4]
Is there a compiled portable version for download somewhere?  Thanks!

**Comment by fleapower** [comment]
I tried running the build with with .NET

`C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe build.xml`

and received several errors.  I also tried removing `<CallTarget Targets="CreateSetup" />` to create a portable version with the same result.

Thanks!

**Comment by fleapower** [comment]
Bump?  Anyone?

**Comment by jdckr** [comment]
It's availabe in the release section https://github.com/jdckr/todotxt.net/releases/tag/todotxt-fork_v1.0

**Comment by fleapower** [comment]
Thanks!
